---
- name: Deploy monitoring page
  hosts: web
  become: yes

  vars:
    hostname: "{{ ansible_hostname }}"
    date: "{{ ansible_date_time.date }}"

  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: restarted
        enabled: yes

    - name: Deploy HTML file
      template:
        src: index.html
        dest: /usr/share/nginx/html/index.html
